## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------
title = "Ariel's Doodles"
theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

#allow for html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  cartWorkerURL = "http://localhost:8787"

[Params.social]

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  arielsdoodles_css = ["css/arielsdoodles.css", "css/cart.css"]



[[menu.main]]
name = "Home"
url = "/"
weight = 10
[[menu.main]]
name = "Cat Calendar"
url = "/calendar/"
weight = 20

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 20

[[menu.main]]
name = "About"
url = "/about/"
weight = 30

[[menu.main]]
name = "Commissions"
url = "/commissions/"
weight = 40

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 50