## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------
title = "Ariel's Doodles"
copyright = "2025"
theme = "hugo-story"


## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  enableShop = false

[Params.social]
  email = "arielchujonart@gmail.com"
  facebook = "https://www.facebook.com/arielchujonart"
  instagram = "https://www.instagram.com/ariel_chujon_art"
  reddit = "https://www.reddit.com/u/arielsdoodles"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  arielsdoodles_cs = ["css/arielsdoodles.css"]

