## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Ariel's Doodle's"
copyright = "2025"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy"]
#googleAnalytics = "G-GFWBYJPVXR"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "You will find portraits of pets, cute Dungeons and Dragons Kitties, and much more."
  logo = "images/banner.jpg"
  favicon = true
  turnstileSiteKey = "0x4AAAAAAB_XENp3OdtwuY8i"
  workerURL = "https://arielsdoodles-form-handler.fchujon.workers.dev"

[Params.social]
  email = "arielchujonart@gmail.com"
  facebook = "https://www.facebook.com/arielchujonart"
  instagram = "https://www.instagram.com/ariel_chujon_art"
  reddit = "https://www.reddit.com/u/arielsdoodles"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  arielsdoodles_cs = ["css/arielsdoodles.css"]