## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------


## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy"]
googleAnalytics = "G-GFWBYJPVXR"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "You will find portraits of pets, cute Dungeons and Dragons Kitties, and much more."
  logo = "images/banner.jpg"
  favicon = true
  turnstileSiteKey = "0x4AAAAAAB_XENp3OdtwuY8i"
  workerURL = "arielsdoodles-form-handler.fchujon.workers.dev"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]


  [[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 20

[[menu.main]]
name = "About"
url = "/about/"
weight = 30

[[menu.main]]
name = "Commissions"
url = "/commissions/"
weight = 40

[[menu.main]]
name = "Contact"
url = "/Contact/"
weight = 40